### PR TITLE
Update Mill 0.11 to 0.11.0-M10

### PR DESCRIPTION
**Pull request by lolgab**

### CODE REVIEW

**Comment by ckipp01** [comment]
I haven't looked closely at all yet, but I see that `mill-scalalib_2.13` is not resolving and a quick check of:

```
cs complete-dep com.lihaoyi:mill-scalalib_2.13:
```
shows me that the newest is `0.11.0-M9` is the latest. Did that change names? I'll dig through the release notes, this is just a lazy ask :D.

**Comment by lolgab** [comment]
It was not yet available on Maven Central. If you re-run the workflow now it should find it.

**Review by ckipp01 — APPROVED** [review]
Thanks a lot @lolgab!

**Comment by ckipp01** [comment]
Alright, so if you were sending this in to use it, [v0.2.3](https://github.com/ckipp01/mill-github-dependency-graph/releases/tag/v0.2.3) is now released, and the default version in the [action](https://github.com/ckipp01/mill-dependency-submission/releases/tag/v1.1.2) is also updated and the v1 tag updated!

**Pull request merged**
